[package]
name = "yarukoto"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
ratatui = "0.30.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.0"
